#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Jul 22 19:43:00 2020

@author: samuel
"""

import numpy as np

class Kernel:
    
    def __init__(self, name):
        
        self.name = name
        
    def evaluate(self, obj1, obj2):

        return 0
    
    def get_Gramm_matrix(self, objects):
        
        return gramm
    
    def get_name(self):
        
        return self.name


class GaussianKernel(Kernel):
    
    
    
class LinearKernel(Kernel):
    
    
    
